/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/CupNew.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CupNew.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
      <mesh geometry={nodes.mesh_0_1.geometry} material={nodes.mesh_0_1.material} />
      <mesh geometry={nodes.mesh_0_2.geometry} material={nodes.mesh_0_2.material} />
      <mesh geometry={nodes.mesh_0_3.geometry} material={nodes.mesh_0_3.material} />
      <mesh geometry={nodes.mesh_0_4.geometry} material={nodes.mesh_0_4.material} />
      <mesh geometry={nodes.mesh_0_5.geometry} material={nodes.mesh_0_5.material} />
    </group>
  )
}

useGLTF.preload('/CupNew.glb')
